# Generated by Django 6.0.6 on 2026-06-25 14:08

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('company', models.CharField(blank=True, max_length=220)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('remote_policy', models.CharField(choices=[('unknown', 'Unknown'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], db_index=True, default='unknown', max_length=24)),
                ('seniority', models.CharField(blank=True, max_length=120)),
                ('compensation', models.CharField(blank=True, max_length=160)),
                ('description_text', models.TextField()),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('application_url', models.URLField(blank=True, max_length=1000)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(db_index=True, default='new', max_length=24)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discovered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('saved', 'Saved'), ('resume_ready', 'Resume Ready'), ('applied', 'Applied'), ('follow_up_due', 'Follow-Up Due'), ('recruiter_screen', 'Recruiter Screen'), ('technical_screen', 'Technical Screen'), ('onsite_final', 'Onsite / Final'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='saved', max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobposting')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('company_page', 'Company Page'), ('ats', 'ATS'), ('api', 'API'), ('rss', 'RSS')], db_index=True, default='manual', max_length=32)),
                ('name', models.CharField(max_length=220)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=32)),
                ('last_message', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.jobsource'),
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('resume', 'Resume'), ('note', 'Note'), ('conversation', 'Conversation'), ('profile', 'Profile'), ('project', 'Project'), ('review', 'Review')], db_index=True, default='note', max_length=24)),
                ('title', models.CharField(max_length=220)),
                ('upload', models.FileField(blank=True, upload_to=core.models.profile_document_upload_to)),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='new', max_length=24)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.profiledocument')),
            ],
            options={
                'ordering': ['document_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact_type', models.CharField(choices=[('skill', 'Skill'), ('achievement', 'Achievement'), ('role', 'Role'), ('project', 'Project'), ('metric', 'Metric'), ('preference', 'Preference'), ('constraint', 'Constraint'), ('education', 'Education')], db_index=True, default='achievement', max_length=32)),
                ('title', models.CharField(max_length=220)),
                ('statement', models.TextField()),
                ('normalized_value', models.CharField(blank=True, max_length=220)),
                ('confidence', models.CharField(default='medium', max_length=24)),
                ('verified_by_user', models.BooleanField(db_index=True, default=False)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='core.profilechunk')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='core.profiledocument')),
            ],
            options={
                'ordering': ['fact_type', 'title', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('canonical', 'Canonical'), ('tailored', 'Tailored')], db_index=True, default='canonical', max_length=24)),
                ('title', models.CharField(max_length=220)),
                ('content_markdown', models.TextField()),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='core.resume')),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='core.jobposting')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('resume_pdf', 'Resume PDF'), ('resume_docx', 'Resume DOCX'), ('resume_markdown', 'Resume Markdown'), ('cover_letter', 'Cover Letter'), ('note', 'Note'), ('export', 'Export')], db_index=True, default='note', max_length=40)),
                ('title', models.CharField(max_length=220)),
                ('file', models.FileField(blank=True, upload_to=core.models.artifact_upload_to)),
                ('content_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.resume')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.resume'),
        ),
        migrations.CreateModel(
            name='ResumeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('support_status', models.CharField(choices=[('supported', 'Supported'), ('user_confirmed', 'User Confirmed'), ('unsupported', 'Unsupported')], db_index=True, default='unsupported', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_claims', to='core.profilefact')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.resume')),
            ],
            options={
                'ordering': ['resume_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('happened_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
                'indexes': [models.Index(fields=['application', 'event_type'], name='core_applic_applica_67fcf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('hard_filter_status', models.CharField(default='pass', max_length=32)),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('missing_requirements', models.JSONField(blank=True, default=list)),
                ('supporting_facts', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(default='medium', max_length=24)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.jobposting')),
            ],
            options={
                'ordering': ['-score', '-computed_at'],
                'indexes': [models.Index(fields=['owner', '-score'], name='core_jobmat_owner_i_2286ce_idx'), models.Index(fields=['owner', 'confidence'], name='core_jobmat_owner_i_189bea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobsource',
            index=models.Index(fields=['owner', 'enabled'], name='core_jobsou_owner_i_56063c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['owner', 'status'], name='core_jobpos_owner_i_35e02f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['owner', 'remote_policy'], name='core_jobpos_owner_i_ba4e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['owner', 'company'], name='core_jobpos_owner_i_e98d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('owner', 'content_hash'), name='core_jobposting_owner_content_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['owner', 'kind'], name='core_profil_owner_i_12bdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['owner', 'status'], name='core_profil_owner_i_70a113_idx'),
        ),
        migrations.AddIndex(
            model_name='profilechunk',
            index=models.Index(fields=['owner', 'document'], name='core_profil_owner_i_d8699d_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefact',
            index=models.Index(fields=['owner', 'fact_type'], name='core_profil_owner_i_77e410_idx'),
        ),
        migrations.AddIndex(
            model_name='profilefact',
            index=models.Index(fields=['owner', 'verified_by_user'], name='core_profil_owner_i_7d20e3_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['owner', 'kind'], name='core_resume_owner_i_43aa3b_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['owner', 'approved'], name='core_resume_owner_i_433db6_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['owner', 'kind'], name='core_artifa_owner_i_18f4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', 'status'], name='core_applic_owner_i_de0c94_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', 'follow_up_at'], name='core_applic_owner_i_27668d_idx'),
        ),
    ]
