# Generated by Django 6.1 on 2026-08-13 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_truth(apps, schema_editor):
    ProfileFact = apps.get_model('core', 'ProfileFact')
    ProfileFact.objects.filter(verified_by_user=True).update(lifecycle='verified')


def reverse_existing_truth(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='artifact',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='freshness_status',
            field=models.CharField(db_index=True, default='fresh', max_length=24),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='source_external_id',
            field=models.CharField(blank=True, db_index=True, max_length=220),
        ),
        migrations.AddField(
            model_name='profilefact',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefact',
            name='evidence_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilefact',
            name='lifecycle',
            field=models.CharField(db_index=True, default='proposed', max_length=24),
        ),
        migrations.AddField(
            model_name='profilefact',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefact',
            name='strength',
            field=models.CharField(default='working', max_length=24),
        ),
        migrations.AddField(
            model_name='profilefact',
            name='user_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('discovered', 'Discovered'), ('saved', 'Saved'), ('approved', 'Approved to Prepare'), ('preparing', 'Preparing Materials'), ('materials_ready', 'Materials Ready'), ('resume_ready', 'Resume Ready'), ('applied', 'Applied'), ('follow_up_due', 'Follow-Up Due'), ('recruiter_screen', 'Recruiter Screen'), ('technical_screen', 'Technical Screen'), ('onsite_final', 'Onsite / Final'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='saved', max_length=32),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('resume_pdf', 'Resume PDF'), ('resume_docx', 'Resume DOCX'), ('resume_markdown', 'Resume Markdown'), ('cover_letter', 'Cover Letter'), ('cover_letter_pdf', 'Cover Letter PDF'), ('cover_letter_html', 'Cover Letter HTML'), ('resume_html', 'Resume HTML'), ('note', 'Note'), ('export', 'Export')], db_index=True, default='note', max_length=40),
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=220)),
                ('professional_summary', models.TextField(blank=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('authorized_countries', models.JSONField(blank=True, default=list)),
                ('work_modes', models.JSONField(blank=True, default=list)),
                ('employment_types', models.JSONField(blank=True, default=list)),
                ('minimum_compensation', models.PositiveIntegerField(blank=True, null=True)),
                ('compensation_currency', models.CharField(default='CAD', max_length=8)),
                ('excluded_companies', models.JSONField(blank=True, default=list)),
                ('completeness', models.PositiveSmallIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Forth concierge', max_length=220)),
                ('status', models.CharField(db_index=True, default='active', max_length=24)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.CharField(choices=[('concierge', 'Forth Concierge'), ('profile', 'Profile Steward'), ('sourcing', 'Sourcing Scout'), ('matching', 'Match Analyst'), ('application', 'Application Coach'), ('documents', 'Document Tailor')], db_index=True, max_length=24)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting for approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=24)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('celery_task_id', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.conversationthread')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('content_markdown', models.TextField()),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='core.jobposting')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.coverletter'),
        ),
        migrations.CreateModel(
            name='JobPostingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('description_text', models.TextField()),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField()),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.jobposting')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['job_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('responsibility', 'Responsibility'), ('credential', 'Credential')], db_index=True, default='required', max_length=24)),
                ('category', models.CharField(db_index=True, default='other', max_length=48)),
                ('text', models.TextField()),
                ('normalized_value', models.CharField(blank=True, max_length=220)),
                ('is_hard', models.BooleanField(db_index=True, default=False)),
                ('weight', models.PositiveSmallIntegerField(default=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.jobposting')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_hard', 'kind', '-weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('eligibility', 'Eligibility'), ('skills', 'Skills'), ('evidence', 'Experience evidence'), ('direction', 'Role direction'), ('domain', 'Domain relevance'), ('logistics', 'Logistics'), ('risk', 'Risk')], db_index=True, max_length=24)),
                ('label', models.CharField(max_length=220)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.jobmatch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight', 'kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('cursor', models.JSONField(blank=True, default=dict)),
                ('log', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.jobsource')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(default='tool', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(db_index=True, default='running', max_length=24)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.agentrun')),
            ],
            options={
                'ordering': ['run_id', 'sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='core_agentstep_run_sequence_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(db_index=True, max_length=48)),
                ('title', models.CharField(max_length=220)),
                ('prompt', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='core.agentrun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'status', 'kind'], name='core_approv_owner_i_477312_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(db_index=True, max_length=48)),
                ('label', models.CharField(max_length=220)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('importance', models.CharField(choices=[('must', 'Must have'), ('strong', 'Strong preference'), ('flexible', 'Flexible'), ('avoid', 'Avoid')], db_index=True, default='flexible', max_length=16)),
                ('verified_by_user', models.BooleanField(db_index=True, default=False)),
                ('rationale', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'label', 'id'],
                'indexes': [models.Index(fields=['owner', 'category', 'importance'], name='core_candid_owner_i_f8f7ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], db_index=True, max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversationthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['owner', 'thread', 'created_at'], name='core_conver_owner_i_cb456f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['owner', 'agent', 'status'], name='core_agentr_owner_i_08b49b_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletter',
            index=models.Index(fields=['owner', 'target_job', 'approved'], name='core_coverl_owner_i_31819f_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobpostingversion',
            constraint=models.UniqueConstraint(fields=('job', 'version'), name='core_jobversion_job_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='jobpostingversion',
            constraint=models.UniqueConstraint(fields=('job', 'content_hash'), name='core_jobversion_job_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='jobrequirement',
            index=models.Index(fields=['owner', 'job', 'kind'], name='core_jobreq_owner_i_dfa063_idx'),
        ),
        migrations.AddIndex(
            model_name='matchsignal',
            index=models.Index(fields=['owner', 'match', 'kind'], name='core_matchs_owner_i_e51141_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerun',
            index=models.Index(fields=['owner', 'source', 'status'], name='core_source_owner_i_f4e988_idx'),
        ),
        migrations.RunPython(migrate_existing_truth, reverse_existing_truth),
    ]
