# Generated by Django 6.0.6 on 2026-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artifact_approved_artifact_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='onboarding_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
