# Generated by Codex on 2026-10-02

from django.db import migrations, models
from django.core.validators import MaxValueValidator, MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_large_halfvec_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='minimum_match_score',
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[MinValueValidator(1), MaxValueValidator(99)],
            ),
        ),
    ]
